group: short_suite
task:
  - name: ifeval
    task: ifeval
    metric_list:
      - metric: prompt_level_strict_accuracy
        aggregation: mean
        higher_is_better: true
  - name: humaneval
    task: humaneval
    metric_list:
      - metric: pass@1
        aggregation: mean
        higher_is_better: true
  - name: mmlu
    task: mmlu
    num_fewshot: 5
    metric_list:
      - metric: acc
        aggregation: mean
        higher_is_better: true
