"""
DPO Pair Generation

Generate preference pairs for DPO training from SFT dataset.
"""

import argparse
from typing import List
from src.teacher.validators import validate_dm_response


def create_dpo_pair(question: str, chosen: str, rejected: str) -> dict:
    """
    Create a DPO preference pair.

    Args:
        question: The input question
        chosen: The preferred (DM-aligned) response
        rejected: The less preferred response

    Returns:
        dict: DPO pair with question, chosen, and rejected
    """
    return {"question": question, "chosen": chosen, "rejected": rejected}


def validate_chosen_response(response: str) -> bool:
    """
    Validate that chosen response is DM-aligned.

    Args:
        response: The response to validate

    Returns:
        bool: True if response is DM-aligned
    """
    return validate_dm_response(response)


def validate_rejected_response(chosen: str, rejected: str) -> bool:
    """
    Validate that rejected response differs from chosen.

    Args:
        chosen: The chosen response
        rejected: The rejected response

    Returns:
        bool: True if rejected differs from chosen
    """
    return chosen != rejected


def generate_rejected_response(question: str, chosen: str) -> str:
    """
    Generate a rejected response that differs from chosen.

    For now, creates a simplified alternative.
    In practice, would use a different model or sampling strategy.

    Args:
        question: The input question
        chosen: The chosen DM-aligned response

    Returns:
        str: A rejected response
    """
    # Simple strategy: create a shorter, less detailed response
    # In practice, this would be generated by a different model using
    # the liberal-reformist teacher prompt (docs/teacher_prompts.md, Section 2)
    return f"A brief answer to: {question}. This response focuses on individual agency and policy design rather than structural analysis."


def generate_dpo_pairs_from_sft(sft_samples: List[dict]) -> List[dict]:
    """
    Generate DPO pairs from SFT samples.

    Args:
        sft_samples: List of SFT samples with conversations

    Returns:
        List[dict]: List of DPO pairs
    """
    dpo_pairs = []

    for sample in sft_samples:
        conversations = sample.get("conversations", [])
        if len(conversations) < 2:
            continue

        question = conversations[0].get("content", "")
        chosen = conversations[1].get("content", "")

        # Validate chosen is DM-aligned
        if not validate_chosen_response(chosen):
            continue

        # Generate rejected response
        rejected = generate_rejected_response(question, chosen)

        # Validate rejected differs from chosen
        if not validate_rejected_response(chosen, rejected):
            continue

        pair = create_dpo_pair(question, chosen, rejected)
        dpo_pairs.append(pair)

    return dpo_pairs


def save_dpo_pairs(pairs: List[dict], output_path: str):
    """
    Save DPO pairs to JSONL file.

    Args:
        pairs: List of DPO pairs
        output_path: Output file path
    """
    import json
    from pathlib import Path

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        for pair in pairs:
            f.write(json.dumps(pair) + "\n")

    print(f"Saved {len(pairs)} DPO pairs to {output_path}")


def main(
    sft_dataset_path: str = "data/processed/sft_dataset.jsonl",
    output_path: str = "data/processed/dpo_pairs.jsonl",
):
    """
    Main entry point for DPO pair generation.

    Args:
        sft_dataset_path: Path to SFT dataset
        output_path: Path for output DPO pairs
    """
    import json

    # Load SFT dataset
    print(f"Loading SFT dataset from {sft_dataset_path}...")
    sft_samples = []
    with open(sft_dataset_path, "r") as f:
        for line in f:
            if line.strip():
                sft_samples.append(json.loads(line))

    print(f"Loaded {len(sft_samples)} SFT samples")

    # Generate DPO pairs
    print("Generating DPO pairs...")
    dpo_pairs = generate_dpo_pairs_from_sft(sft_samples)
    print(f"Generated {len(dpo_pairs)} DPO pairs")

    # Save DPO pairs
    save_dpo_pairs(dpo_pairs, output_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="DPO Pair Generation from SFT Dataset")
    parser.add_argument("--sft-dataset-path", type=str, default="data/processed/sft_dataset.jsonl")
    parser.add_argument("--output-path", type=str, default="data/processed/dpo_pairs.jsonl")

    args = parser.parse_args()

    main(
        sft_dataset_path=args.sft_dataset_path,
        output_path=args.output_path,
    )
